import PDFDocument from 'pdfkit';
import type { SymmetryAnalysis, Chord, PitchClass } from '@musical-symmetry/core';
import { chordLabel, groupSummary } from './pdf-templates.js';

interface AnalysisEntry {
  analysis: SymmetryAnalysis;
  chord: Chord | null;
  pitchClasses: PitchClass[];
  beat?: number;
}

interface ReportOptions {
  title: string;
  filename?: string;
  analyses: AnalysisEntry[];
}

export async function generateAnalysisReport(options: ReportOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('Musical Symmetry', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(14).font('Helvetica').fillColor('#666').text('Analysis Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text(options.title, { align: 'center' });

    if (options.filename) {
      doc.moveDown(0.2);
      doc.fontSize(10).font('Helvetica').fillColor('#888').text(`Source: ${options.filename}`, { align: 'center' });
    }

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#ddd');
    doc.moveDown(0.5);

    for (let i = 0; i < options.analyses.length; i++) {
      const entry = options.analyses[i];
      if (!entry) continue;
      const label = chordLabel(entry.pitchClasses, entry.chord);

      if (doc.y > 680) doc.addPage();

      const sectionTitle = entry.beat !== undefined ? `Beat ${entry.beat}: ${label}` : `${label}`;
      doc.fontSize(13).font('Helvetica-Bold').fillColor('#1e293b').text(sectionTitle);
      doc.moveDown(0.3);

      doc.fontSize(9).font('Courier').fillColor('#334155');
      doc.text(groupSummary(entry.analysis));
      doc.moveDown(0.5);

      if (i < options.analyses.length - 1) {
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#eee');
        doc.moveDown(0.5);
      }
    }

    doc.moveDown(1);
    doc.fontSize(8).font('Helvetica').fillColor('#aaa')
      .text(`Generated by Musical Symmetry | symmetry.tendrid.us | ${new Date().toISOString().split('T')[0]}`, { align: 'center' });

    doc.end();
  });
}
