import Foundation

/// One recorded case from `packages/core/test-vectors.json`.
///
/// The file is generated by the TypeScript engine and is the specification
/// this port is held to — see docs/specs/2026-09-21-ios-native-v1-design.md §2.1.
/// Never edit it by hand; regenerate with `npm -w packages/core run vectors`.
struct Vector {
    let name: String
    let args: [Any]
    let value: Any

    /// Decodes every element as an `NSNumber`, or fails (returns `nil`) as a
    /// whole. `compactMap` would silently DROP a non-number element instead,
    /// turning a malformed vector into a shorter array that can happen to
    /// compare equal to the expected result — a corrupt fixture must fail
    /// loudly, not pass by accident.
    func intArrayArg(_ index: Int) -> [Int]? {
        guard index < args.count, let raw = args[index] as? [Any] else { return nil }
        var result: [Int] = []
        result.reserveCapacity(raw.count)
        for element in raw {
            guard let number = (element as? NSNumber)?.intValue else { return nil }
            result.append(number)
        }
        return result
    }

    /// See `intArrayArg` — same all-or-nothing decoding, applied to `value`.
    var intArrayValue: [Int]? {
        guard let raw = value as? [Any] else { return nil }
        var result: [Int] = []
        result.reserveCapacity(raw.count)
        for element in raw {
            guard let number = (element as? NSNumber)?.intValue else { return nil }
            result.append(number)
        }
        return result
    }
}

enum Vectors {
    /// Resolved relative to this source file so the tests do not depend on the
    /// working directory swift test happens to be run from.
    private static var fileURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // ChrometriaCoreTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // core-swift
            .deletingLastPathComponent()   // packages
            .appendingPathComponent("core/test-vectors.json")
    }

    // `nonisolated(unsafe)` is safe here, not just silenced: Swift's lazy static
    // initialization runs this closure exactly once, and `all` is never mutated
    // afterward, so concurrent XCTest readers only ever see a fully-built,
    // immutable array. This is test-only scaffolding, not the shipping library
    // target. If this global is ever made mutable, this annotation would hide a
    // real data race — remove it at that point.
    nonisolated(unsafe) private static let all: [Vector] = {
        guard let data = try? Data(contentsOf: fileURL),
              let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let raw = root["vectors"] as? [[String: Any]]
        else { return [] }
        return raw.compactMap { entry in
            guard let name = entry["name"] as? String else { return nil }
            return Vector(name: name,
                          args: entry["args"] as? [Any] ?? [],
                          value: entry["value"] as Any)
        }
    }()

    static func cases(for name: String) throws -> [Vector] {
        let matching = all.filter { $0.name == name }
        // An empty result means a typo'd name or a missing file, and would make
        // a test vacuously pass. Fail loudly instead.
        if matching.isEmpty {
            throw NSError(domain: "Vectors", code: 1, userInfo: [
                NSLocalizedDescriptionKey:
                    "no vectors named \(name) — check the spelling and that " +
                    "packages/core/test-vectors.json exists"])
        }
        return matching
    }
}
